#!/usr/bin/env bash
# Script to configure Nginx to listen on port 80

# Update Nginx configuration to listen on port 80
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Restart Nginx service to apply changes
service nginx restart
