#!/usr/bin/env bash
# This script configures the localhost and facebook.com IP addresses

# Copy hosts file to a temporary location
cp /etc/hosts ~/hosts.new

# Replace localhost IP address with 127.0.0.2
sed -i 's/^127\.0\.0\.1[[:space:]]localhost$/127.0.0.2 localhost/' ~/hosts.new

# Replace facebook.com IP address with 8.8.8.8
sed -i 's/^.*facebook\.com$/8.8.8.8 facebook.com/' ~/hosts.new

# Copy the modified hosts file back to /etc/hosts
sudo cp -f ~/hosts.new /etc/hosts
