#!/usr/bin/env bash
# This script configures Nginx to run as the nginx user and listen on port 8080

sed -i 's/user\s*\(.*\);/user nginx;/' /etc/nginx/nginx.conf

sed -i 's/listen\s*\(.*\);/listen 8080;/' /etc/nginx/conf.d/default.conf

service nginx restart
