#!/usr/bin/env bash
# This script configures Nginx to run as the nginx user and listen on port 8080
sed -i 's/user .*/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen .*/listen 8080;/' /etc/nginx/sites-available/default
if ! grep -q "daemon off;" /etc/nginx/nginx.conf; then
echo "daemon off;" >> /etc/nginx/nginx.conf
fi
chown -R nginx:nginx /var/lib/nginx
service nginx restart
